config/routes.rb
Toolkit::Application.routes.draw do

  delete 'users' => redirect('/')

  devise_for :users

  resources :clouds do
    resources :server_types, :storage_types, :database_types, :data_transfers
  end

  resources :additional_costs do
    post 'clone', :on => :member
  end

  resources :reports do
    post 'print', 'regenerate', :on => :member
  end

  resources :pattern_maps do
    put 'multi_update', :on => :collection
  end

  resources :patterns do
    post 'clone', :on => :member
    resources :rules do
      post 'clone', 'move_higher', 'move_lower', :on => :member
    end
  end

  resources :deployments do
    post 'clone', :on => :member
    resources :servers, :storages, :database_resources, :remote_nodes, :data_links, :additional_costs_deployments,
              :applications, :data_chunks do
      post 'clone', :on => :member
    end
  end

  get 'dashboard' => 'dashboard#index', :as => 'user_root'
  root :to => 'home#index'
  match '*url', :to => 'application#render_404'
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  belongs_to :deployment
  belongs_to :server

  include ModelMixins::PatternMixin
  include ModelMixins::DataLinkMixin

  # server_id should always be present but deployment.deep_clone fails so we'll enforce it in the UI
  validates :user_id, :deployment_id, :name, :presence => true
  validates :instance_hour_monthly_baseline, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 744 }
  validate :check_server

  attr_accessible :name, :description, :instance_hour_monthly_baseline, :server_id

  after_initialize :set_defaults

  def deep_clone(options={})
    Application.transaction do
      new_application = self.dup(:include => [:pattern_maps], :use_dictionary => true)
      new_application.name = options[:name] || "Copy of #{new_application.name}"
      new_application.save!(:validate => false)
      new_application
    end
  end

  private
  def check_server
    errors.add(:server, 'must be in the same deployment as the application') if self.server_id && !self.deployment.servers.exists?(self.server_id)
  end

  def set_defaults
    if new_record?
      self.instance_hour_monthly_baseline ||= 0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_user_time_zone
  layout 'application'

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception, :with => :render_error
  end

  # Rails 3 needs a hack for 404 errors to be displayed, see last route
  def render_404()
    logger.error("\n\n404 error for #{params[:url]}")
    render :template => "/errors/404.html.erb", :status => 404
  end

  private
  def set_user_time_zone
    Time.zone = current_user.timezone if user_signed_in?
  end

  def render_error(exception)
    logger.error("\n\n#{exception.class.to_s} (#{exception.message.to_s}):\n#{exception.backtrace}")
    notify_airbrake(exception)
    render :template => "/errors/500.html.erb", :status => 500
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_deployment, :only => [:index, :show, :update, :create, :destroy, :clone]
  before_filter :load_application, :only => [:update, :destroy, :clone]

  def index
    load_applications
    @application = current_user.applications.new
  end

  def show
    redirect_to deployment_application_url(@deployment)
  end

  def update
    if @application.update_attributes(params[:application])
      head :ok
    else
      render :json => @application.errors.full_messages, :status => :unprocessable_entity
    end
  end

  def create
    # Hack: force server_id to be set since we can't do it in model validations
    unless params[:application][:server_id]
      redirect_to deployment_applications_url(@deployment), :flash => {:error => 'Please create a server before creating applications.'}
      return true
    end

    @application = current_user.applications.new(params[:application])
    @application.deployment = @deployment
    if @application.save
      redirect_to deployment_applications_url(@deployment), :flash => {:success => 'Application was created.'}
    else
      load_applications
      render :index
    end
  end

  def destroy
    @application.destroy
    redirect_to deployment_applications_url(@deployment), :flash => {:success => 'Application was deleted.'}
  end

  def clone
    begin
      @application.deep_clone
      redirect_to deployment_applications_url(@deployment), :flash => {:success => 'Application was cloned.'}
    rescue
      redirect_to deployment_applications_url(@deployment), :flash => {:error => 'Application could not be cloned.'}
    end
  end

  private
  def load_deployment
    @deployment = current_user.deployments.find(params[:deployment_id])
  end

  def load_application
    @application = @deployment.applications.find(params[:id])
  end

  def load_applications
    @applications = @deployment.applications.page(params[:page]).order('name')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title, page_title.to_s)
  end

  def header(header, page_title=nil, help='')
    page_title = header unless page_title
    title(page_title)
    html = "<div class='row'><div class='span10'><h2>".html_safe
    html << header.to_s
    html << "</h2></div><div class='span2 offset4' style='padding-top:10px; text-align:right'><span class='label warning dropdown-toggle' id='help_button' style='cursor:pointer'>Help</span></div></div></div>".html_safe
    html << "<div class='alert-message block-message warning' id='help' style='display:none'>".html_safe
    html << help.html_safe
    html << "</div><br/>".html_safe
    content_for(:header, html)
  end

  def editable_header(header_object, help='')
    if header_object.has_attribute?(:name)
      title(header_object.name)
      html = "<div class='row'><div class='span14'><h2>".html_safe
      html << "#{header_object.class.to_s.underscore.humanize} - "
      html << (best_in_place header_object, :name)
      html << " <small>#{(best_in_place header_object, :description, :type => :textarea, :nil => 'Click to add a description')}</small>".html_safe if header_object.has_attribute?(:description)
      html << "</h2></div><div class='span2' style='padding-top:10px; text-align:right'><span class='label warning dropdown-toggle' id='help_button' style='cursor:pointer'>Help</span></div></div></div>".html_safe
    end
    html << "<div class='alert-message block-message warning' id='help' style='display:none'>".html_safe
    html << help.html_safe
    html << "</div><br/>".html_safe
    content_for(:header, html)
  end

  def jq_button(title, icon, icon_corner, link_object, options={})
    corner_class = "ui-corner-#{icon_corner}" if icon_corner
    link_to raw("<span class='ui-button-icon-primary ui-icon ui-icon-#{icon}'></span><span class='ui-button-text'>#{title}</span>"), link_object,
            {:class => "ui-button ui-button-icon-only ui-widget ui-state-default #{corner_class}", :title => title, :rel => 'twipsy'}.merge(options)
  end

  def pattern_button(patterns_hash)
    "<span class='label success dropdown-toggle pattern_button'>#{patterns_hash[:selected_patterns_count]} Patterns</span>".html_safe
  end

  def report_button(button_name)
    "<span class='label success dropdown-toggle report_button'>#{button_name}</span>".html_safe
  end
end

app/views/applications/index.html.erb
<% editable_header @deployment, <<HELP
<p>This page can be used to model the applications or programs in a system. Applications are deployed on servers,
where their running hours are added to for cost calculations. For example, if there are 2 applications and the first one
runs for 8 hours per day (09:00-17:00) whilst the second one runs for 1 hour every night, then the server hosting the
applications will need to run for 8 + 1 * 30 = 270 hours per month.
The data transfer to and from applications is also mapped to the server hosting them.</p>
HELP
%>

<%= render :partial => 'shared/form_errors', :locals => {:model => @application} %>
<%= render :partial => 'shared/deployment_menu' %>

<table class="condensed-table bordered-table">
  <thead>
    <tr>
      <th class="span5">Name</th>
      <th class="span5">Description</th>
      <th>Hours/Month</th>
      <th class="span5">Server</th>
      <th class="span2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <% patterns_hash = application.get_all_patterns_ordered(:instance_hour_monthly_baseline) %>
      <tr>
        <td><%= best_in_place application, :name, :path => deployment_application_path(@deployment, application) %></td>
        <td><%= best_in_place application, :description, :type => :textarea, :path => deployment_application_path(@deployment, application) %></td>
        <td><%= best_in_place application, :instance_hour_monthly_baseline, :path => deployment_application_path(@deployment, application), :inner_class => 'span2' %>
            <%= pattern_button patterns_hash %>
        </td>
        <td><%= best_in_place application, :server_id, :type => :select, :path => deployment_application_path(@deployment, application),
                                           :collection => @deployment.servers.collect{|s| [s.id, s.name]} %></td>
        <td><div class="ui-buttonset">
            <%= jq_button 'Clone', 'copy', 'left', clone_deployment_application_path(@deployment, application), :method => :post %>
            <%= jq_button 'Delete', 'closethick', 'right', deployment_application_path(@deployment, application), :confirm => "OK to delete?", :method => :delete %>
        </div></td>
      </tr>
      <%= render :partial => 'shared/pattern_attachment', :locals => {
              :patternable => application, :patterns_hash => patterns_hash } %>
  <% end %>

    <tr>
      <%= form_for [@deployment, @application] do |f| %>
        <td><%= f.text_field :name, :class => (@application.errors.include?(:name) ? "f_error": "") %></td>
        <td><%= f.text_field :description, :class => (@application.errors.include?(:description) ? "f_error": "") %></td>
        <td><%= f.number_field :instance_hour_monthly_baseline,
                               :class => "span2 #{@application.errors.include?(:instance_hour_monthly_baseline) ? "f_error": ""}",
                               :rel => "popover", "data-content" => "The baseline number of hours that the application will be running every month, e.g. 744 hours if it runs 24 hours per day." %></td>
        <td><%= f.collection_select :server_id, @deployment.servers.order(:name), :id, :name,
                                    {}, {:class => (@application.errors.include?(:server_id) ? "f_error": ""),
                                         :rel => "popover", "data-content" => "The server that hosts the application."} %></td>
        <td><%= f.submit "Create", :class =>'btn primary' %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<%= will_paginate @applications %>