config/routes.rb
Toolkit::Application.routes.draw do

  delete 'users' => redirect('/')

  devise_for :users

  resources :clouds do
    resources :server_types, :storage_types, :database_types, :data_transfers
  end

  resources :additional_costs do
    post 'clone', :on => :member
  end

  resources :reports do
    post 'print', 'regenerate', :on => :member
  end

  resources :pattern_maps do
    put 'multi_update', :on => :collection
  end

  resources :patterns do
    post 'clone', :on => :member
    resources :rules do
      post 'clone', 'move_higher', 'move_lower', :on => :member
    end
  end

  resources :deployments do
    post 'clone', :on => :member
    resources :servers, :storages, :database_resources, :remote_nodes, :data_links, :additional_costs_deployments,
              :applications, :data_chunks do
      post 'clone', :on => :member
    end
  end

  get 'dashboard' => 'dashboard#index', :as => 'user_root'
  root :to => 'home#index'
  match '*url', :to => 'application#render_404'
end

app/views/shared/_cloud_menu.html.erb
<ul class="tabs">
  <li <%= "class='active'" if controller.controller_name == 'server_types' %>><%= link_to 'Server Types', cloud_server_types_path(@cloud) %></li>
  <li <%= "class='active'" if controller.controller_name == 'storage_types' %>><%= link_to 'Storage Types', cloud_storage_types_path(@cloud) %></li>
  <li <%= "class='active'" if controller.controller_name == 'database_types' %>><%= link_to 'Database Types', cloud_database_types_path(@cloud) %></li>
  <li <%= "class='active'" if controller.controller_name == 'data_transfers' %>><%= link_to 'Data Transfer', cloud_data_transfers_path(@cloud) %></li>
</ul>

app/views/shared/_deployment_menu.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to 'Cost Report', new_report_path(:report => {:reportable_type => 'Deployment', :reportable_id => @deployment.id}), :class => 'btn' %>
    <span class="divider"></span>
  </li>
  <li>
    <%= link_to 'Clone Deployment', clone_deployment_path(@deployment), :method => :post, :class => 'btn' %>
    <span class="divider"></span>
  </li>
  <li>
    <%= link_to 'Delete Deployment', @deployment, :confirm => "OK to delete? All of the deployment's resources will also be deleted.",
                :method => :delete, :class => 'btn' %>
  </li>
</ul>

<ul class="tabs">
  <li <%= "class='active'" if controller.controller_name == 'servers' %>><%= link_to 'Servers', deployment_servers_path(@deployment) %></li>
  <li <%= "class='active'" if controller.controller_name == 'storages' %>><%= link_to 'Storage', deployment_storages_path(@deployment) %></li>
  <li <%= "class='active'" if controller.controller_name == 'database_resources' %>><%= link_to 'Databases', deployment_database_resources_path(@deployment) %></li>
  <li <%= "class='active'" if controller.controller_name == 'remote_nodes' %>><%= link_to 'Remote Nodes', deployment_remote_nodes_path(@deployment) %></li>
  <li <%= "class='active'" if controller.controller_name == 'data_links' %>><%= link_to 'Data Transfer', deployment_data_links_path(@deployment) %></li>
  <li <%= "class='active'" if controller.controller_name == 'additional_costs_deployments' %>><%= link_to 'Additional Costs', deployment_additional_costs_deployments_path(@deployment) %></li>
</ul>

app/views/shared/_form_errors.html.erb
<% unless model.nil? || model.errors.empty? %>
  <div id="form_error_modal" class="modal hide fade" style="display: none; ">
    <div class="modal" style="position: relative; top: auto; left: auto; margin: 0 auto; z-index: 1">
      <div class="modal-header">
        <a href="#" class="close">×</a>
        <h3>There is a problem with the form...</h3>
      </div>
      <div class="modal-body">
        <strong>Fix the following errors and try again:</strong>
        <ul>
          <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <a href="#" onclick="$('#form_error_modal').modal('hide')" class="btn primary">&nbsp;&nbsp;&nbsp; OK &nbsp;&nbsp;&nbsp;</a>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<ul class="nav">
  <li><%= link_to 'Clouds', clouds_path %></li>
  <li><%= link_to 'Deployments', deployments_path %></li>
  <li><%= link_to 'Additional Costs', additional_costs_path %></li>
  <li><%= link_to 'Patterns', patterns_path %></li>
  <li><%= link_to 'Reports', reports_path %></li>
</ul>
<p class="pull-right">
  | <%= link_to 'Update Account', edit_user_registration_path %> |
  <%= link_to 'Logout', destroy_user_session_path, :method => :delete %> |
</p>

app/views/shared/_pattern_attachment.html.erb
<% # This partial view needs the following 2 local variables to be set:
# patternable: the active record object that the pattern applies to (e.g. an application or server)
# patterns_hash: the hash from the pattern_mixin's get_all_patterns_ordered method
%>
<tr style="display:none">
  <%= form_for(PatternMap.new, :url => multi_update_pattern_maps_path, :method => :put) do |f| %>
    <%= f.hidden_field :patternable_type, :value => patternable.class.to_s %>
    <%= f.hidden_field :patternable_id, :value => patternable.id %>
    <%= f.hidden_field :patternable_attribute, :value => patterns_hash[:attribute] %>

    <td colspan="100%" style="padding: 0; padding-left: 200px;">
      <div class="row">
        <div class="span13">
          <% # If the selected_pattens_count is 0, then nothing is selected, otherwise the first N items are selected
             # but since the array index starts with 0, we must select the first N-1 items %>
          <%= f.select(:pattern, options_for_select(patterns_hash[:all_patterns].map{|p| [p.name, p.id]},
                                                    (patterns_hash[:selected_patterns_count] == 0 ? [] : patterns_hash[:all_patterns][0..patterns_hash[:selected_patterns_count]-1].collect{|p| p.id})),
                       {}, :multiple => true, :class => 'multiselect') %>
        </div>
        <div class="span5" style="margin-top:65px;">
          <%= f.submit 'Save Changes', :class => 'btn primary' %>
        </div>
      </div>
    </td>
  <% end %>
</tr>

app/views/shared/_pattern_menu.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to 'Clone Pattern', clone_pattern_path(@pattern), :method => :post, :class => 'btn' %>
    <span class="divider"></span>
  </li>
  <li>
    <%= link_to 'Delete Pattern', @pattern, :confirm => "OK to delete? All of the pattern's rules will also be deleted.",
                :method => :delete, :class => 'btn' %>
  </li>
</ul>

<ul class="tabs">
  <li <%= "class='active'" if controller.controller_name == 'rules' %>><%= link_to 'Rules', pattern_rules_path(@pattern) %></li>
  <li><a href="#">Referenced By</a></li>
</ul>