config/routes.rb
Toolkit::Application.routes.draw do

  delete 'users' => redirect('/')

  devise_for :users

  resources :clouds do
    resources :server_types, :storage_types, :database_types, :data_transfers
  end

  resources :additional_costs do
    post 'clone', :on => :member
  end

  resources :reports do
    post 'print', 'regenerate', :on => :member
  end

  resources :pattern_maps do
    put 'multi_update', :on => :collection
  end

  resources :patterns do
    post 'clone', :on => :member
    resources :rules do
      post 'clone', 'move_higher', 'move_lower', :on => :member
    end
  end

  resources :deployments do
    post 'clone', :on => :member
    resources :servers, :storages, :database_resources, :remote_nodes, :data_links, :additional_costs_deployments,
              :applications, :data_chunks do
      post 'clone', :on => :member
    end
  end

  get 'dashboard' => 'dashboard#index', :as => 'user_root'
  root :to => 'home#index'
  match '*url', :to => 'application#render_404'
end

app/models/remote_node.rb
class RemoteNode < ActiveRecord::Base
  belongs_to :user
  belongs_to :deployment

  include ModelMixins::DataLinkMixin

  validates :user_id, :deployment_id, :name, :presence => true

  attr_accessible :name, :description

  def display_class
    "Remote Node"
  end
end

app/controllers/remote_nodes_controller.rb
class RemoteNodesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_deployment, :only => [:index, :show, :update, :create, :destroy]
  before_filter :load_remote_node, :only => [:update, :destroy]

  def index
    load_remote_nodes
    @remote_node = current_user.remote_nodes.new
  end

  def show
    redirect_to deployment_remote_nodes_url(@deployment)
  end

  def update
    if @remote_node.update_attributes(params[:remote_node])
      head :ok
    else
      render :json => @remote_node.errors.full_messages, :status => :unprocessable_entity
    end
  end

  def create
    @remote_node = current_user.remote_nodes.new(params[:remote_node])
    @remote_node.deployment = @deployment

    if @remote_node.save
      redirect_to deployment_remote_nodes_url(@deployment), :flash => {:success => 'Remote node was created.'}
    else
      load_remote_nodes
      render :index
    end
  end

  def destroy
    @remote_node.destroy
    redirect_to deployment_remote_nodes_url(@deployment), :flash => {:success => 'Remote node was deleted.'}
  end

  private
  def load_deployment
    @deployment = current_user.deployments.find(params[:deployment_id])
  end

  def load_remote_node
    @remote_node = @deployment.remote_nodes.find(params[:id])
  end

  def load_remote_nodes
    @remote_nodes = @deployment.remote_nodes.page(params[:page]).order('name')
  end
end

app/views/remote_nodes/index.html.erb
<% editable_header @deployment, <<HELP
<p>This page can be used to model the remote nodes in a deployment, which are useful when modelling the data transfer
between any resource in the deployment and external nodes. Remote nodes can be anything that require data transfer
to and from your deployment such as users or applications outside of your deployment.</p>
HELP
%>

<%= render :partial => 'shared/form_errors', :locals => {:model => @remote_node} %>
<%= render :partial => 'shared/deployment_menu' %>

<table class="condensed-table bordered-table">
  <thead>
    <tr>
      <th class="span8">Name</th>
      <th class="span15">Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @remote_nodes.each do |node| %>
      <tr>
        <td><%= best_in_place node, :name, :path => deployment_remote_node_path(@deployment, node), :inner_class => 'span7' %></td>
        <td><%= best_in_place node, :description, :type => :textarea, :path => deployment_remote_node_path(@deployment, node), :html_attrs => {:class => 'span14'} %></td>
        <td><div class="ui-buttonset">
            <%= jq_button 'Delete', 'closethick', 'all', deployment_remote_node_path(@deployment, node), :confirm => "OK to delete?", :method => :delete %>
        </div></td>
      </tr>
  <% end %>

    <tr>
      <%= form_for [@deployment, @remote_node] do |f| %>
        <td><%= f.text_field :name, :class => "span7 #{@remote_node.errors.include?(:name) ? "f_error": ""}" %></td>
        <td><%= f.text_field :description, :class => "span14 #{@remote_node.errors.include?(:description) ? "f_error": ""}" %></td>
        <td><%= f.submit "Create", :class =>'btn primary' %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<%= will_paginate @remote_nodes %>