config/routes.rb
Toolkit::Application.routes.draw do

  delete 'users' => redirect('/')

  devise_for :users

  resources :clouds do
    resources :server_types, :storage_types, :database_types, :data_transfers
  end

  resources :additional_costs do
    post 'clone', :on => :member
  end

  resources :reports do
    post 'print', 'regenerate', :on => :member
  end

  resources :pattern_maps do
    put 'multi_update', :on => :collection
  end

  resources :patterns do
    post 'clone', :on => :member
    resources :rules do
      post 'clone', 'move_higher', 'move_lower', :on => :member
    end
  end

  resources :deployments do
    post 'clone', :on => :member
    resources :servers, :storages, :database_resources, :remote_nodes, :data_links, :additional_costs_deployments,
              :applications, :data_chunks do
      post 'clone', :on => :member
    end
  end

  get 'dashboard' => 'dashboard#index', :as => 'user_root'
  root :to => 'home#index'
  match '*url', :to => 'application#render_404'
end

app/models/report.rb
class Report < ActiveRecord::Base
  USER_REPORTABLE_MODELS = ['Deployment']
  REPORT_STATUSES = ['Pending', 'Processing', 'Completed', 'Failed']

  belongs_to :user
  belongs_to :reportable, :polymorphic => true

  validates :user_id, :name, :reportable_id, :reportable_type, :presence => true
  validates :start_date, :date => {:after => Time.new(2011, 12, 31),
                                   :message => "can't be earlier than 2012-01 as we don't have pricing details for earlier dates"}
  validates :end_date, :date => {:after => :start_date}
  validate :check_date_range

  attr_accessible :name, :description, :start_date, :end_date
  before_destroy :updatable?

  default_scope select((column_names - ['xml', 'html']).map { |column_name| "\"#{table_name}\".\"#{column_name}\""})

  def check_date_range
    errors.add(:end_date, 'is invalid. Maximum reporting period is 10 years') if start_date && end_date &&
        Time.diff(start_date, end_date)[:year] > 10
  end

  def display_start_date
    start_date.strftime("%Y-%m")
  end

  def display_end_date
    end_date.strftime("%Y-%m")
  end

  def updatable?
    ['Completed', 'Failed'].include? self.status
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_report, :only => [:update, :destroy, :regenerate]
  before_filter :check_reportable_type, :only => [:new, :create]

  def index
    @reports = current_user.reports.page(params[:page]).order('completed_at DESC')
  end

  def show
    load_report_with_html
    redirect_to reports_url, :flash => {:warning => 'Report is either still being processed or has failed and cannot be viewed.'} unless @report.status == 'Completed'
  end

  def print
    load_report_with_html
    if @report.status == 'Completed'
      render :show
    else
      redirect_to reports_url, :flash => {:warning => 'Report is still being processed, it can only be printed once completed.'}
    end
  end

  def update
    # Hack to allow users to update the report dates with best_in_place, YUCK!
    start_date = params[:report].delete(:display_start_date)
    end_date = params[:report].delete(:display_end_date)
    if start_date || end_date
      if @report.updatable?
        if start_date
          if start_date =~ /\A\d{4}-\d{2}\z/
            params[:report][:start_date] = start_date + '-01'
          else
            render :json => ["Report date format must be YYYY-MM"], :status => :unprocessable_entity
            return
          end
        end
        if end_date
          if end_date =~ /\A\d{4}-\d{2}\z/
            params[:report][:end_date] = end_date + '-01'
          else
            render :json => ["Report date format must be YYYY-MM"], :status => :unprocessable_entity
            return
          end
        end
      else
        render :json => ["Report dates cannot be updated as the report is still being processed."], :status => :unprocessable_entity
        return
      end
    end
    # End of hack

    if @report.update_attributes(params[:report])
      head :ok
    else
      render :json => @report.errors.full_messages, :status => :unprocessable_entity
    end
  end

  def new
    @report = current_user.reports.new
    if params[:report][:reportable_id]
      reportable = get_reportable
      # Regenerate the report if it one already exists
      if reportable.report
        @report = reportable.report
        regenerate
        return
      end

      @report.reportable = reportable
    else
      @report.reportable_type = params[:report][:reportable_type]
    end
    load_reportables
  end

  def create
    # Hack to allow users to set year-month dates for the report
    params[:report][:start_date] = params[:report][:start_date] + '-01' if params[:report][:start_date]
    params[:report][:end_date] = params[:report][:end_date] + '-01' if params[:report][:end_date]
    @report = current_user.reports.new(params[:report])

    reportable = get_reportable
    if reportable.report
      redirect_to reports_url, :flash => {:error => 'A report already exists for that source, you can regenerate it if needed.'}
      return
    end

    @report.reportable = reportable
    if @report.save
      Delayed::Job.enqueue(Reports::Job.new(@report))
      redirect_to reports_url, :flash => {:success => 'Report is being created, this should only take a minute...'}
    else
      load_reportables
      render :new
    end
  end

  def destroy
    if @report.destroy
      redirect_to reports_url, :flash => {:success => 'Report was deleted.'}
    else
      redirect_to reports_url, :flash => {:warning => 'Report is still being processed, it can only be deleted once completed.'}
    end
  end

  def regenerate
    if @report.updatable?
      Delayed::Job.enqueue(Reports::Job.new(@report))
      redirect_to reports_url, :flash => {:success => 'Report is being regenerated, this should only take a minute...'}
    else
      redirect_to reports_url, :flash => {:warning => 'Report is still being processed, it can only be regenerated once completed.'}
    end
  end

  private
  def load_report
    @report = current_user.reports.find(params[:id])
  end

  def check_reportable_type
    raise AppExceptions::InvalidParameter.new("Reports can only be created from user models.") unless
        Report::USER_REPORTABLE_MODELS.include?(params[:report][:reportable_type])
  end

  def load_reportables
    @reportables = params[:report][:reportable_type].constantize.where('user_id = ?', current_user.id).order(:name)
  end

  def get_reportable
    reportable = params[:report][:reportable_type].constantize.where(
        'id = ? AND user_id = ?', params[:report][:reportable_id], current_user.id).first
    raise ActiveRecord::RecordNotFound unless reportable
    reportable
  end

  def load_report_with_html
    @report = current_user.reports.find(params[:id], :select => :html)
  end
end

app/views/reports/index.html.erb
<% header 'Reports', nil, <<HELP
<p>This page lists the reports that you've created. Reports can be created from various models such as deployments.
For example, a cost report for a deployment would show how the cost of that deployment would change during the reporting period
(based on any patterns used). Reports are based on the state of their source model at the time that the report was created. So if
you change a deployment, you should regenerate the report to reflect the changes in the deployment.
Reports can take a while to process as they involve many calculations.</p>
HELP
%>

<ul class="breadcrumb">
  <li>
    <%= link_to 'New Cost Report', new_report_path(:report => {:reportable_type => 'Deployment'}), :class => 'btn' %>
    <span class="divider"></span>
  </li>
</ul>

<table class="condensed-table bordered-table zebra-striped">
  <thead>
    <tr>
      <th class="span5">Name</th>
      <th class="span6">Description</th>
      <th>Source</th>
      <th>Report period</th>
      <th>Generated at</th>
      <th class="span3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>
          <%= if report.status == 'Completed'
                jq_button 'Open', 'folder-open', 'all', report
              elsif report.status == 'Failed'
                jq_button 'Report failed, please contact us.', 'alert', 'all', reports_path
              else
                image_tag "spinning.gif", :class => 'refresh', :rel => 'link_twipsy', :title => 'Generating report, page will auto-refresh'
          end %>
          <%= best_in_place report, :name, :inner_class => 'span3' %>
        </td>
        <td style="vertical-align: middle"><%= best_in_place report, :description, :type => :textarea, :html_attrs => {:class => 'span6'} %></td>
        <td><%= link_to (report.reportable.name ? report.reportable.name : report.reportable.id),
                        report.reportable %> <%= "(#{report.reportable_type.titleize})" if current_user.beta_user? %></td>
        <td><%= best_in_place report, :display_start_date, :inner_class => 'span2 report_date' %> to
          <%= best_in_place report, :display_end_date, :inner_class => 'span2 report_date' %></td>
        <td><%= report.status == 'Completed' ? report.completed_at : report.status %></td>
        <td><div class="ui-buttonset">
          <%= jq_button 'Print', 'print', 'left', print_report_path(report), :method => :post %>
          <%= jq_button 'Regenerate report', 'arrowrefresh-1-s', nil, regenerate_report_path(report), :method => :post %>
          <%= jq_button 'Delete', 'closethick', 'right', report, :confirm => "OK to delete?", :method => :delete %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  var field_updated = "<span class='flash-success'>Please regenerate a report if you change its reporting period and would like to update the report</span>";
  var alerted = false;
  $(function() {
    $('span.best_in_place[data-attribute=display_start_date||display_end_date]').bind("ajax:success", function(){
      if (!alerted) {
        $(field_updated).purr({removeTimer: 8000});
        alerted = true;
      }
    });

    if ($('img.refresh').size() > 0)
      window.setTimeout('location.reload()', 5000);
  });
</script>

<%= will_paginate @reports %>

app/views/reports/new.html.erb
<% header 'New Report', nil, <<HELP
<p>Reports can be created from various models such as deployments. Reports are created by running
simulations between a start and end date, and analysing the patterns used in the models. For example, a cost
report for a deployment would show how the cost of that deployment would change over time based on its patterns.</p>
HELP
%>

<%= render :partial => 'shared/form_errors', :locals => {:model => @report} %>

<div class="row">
  <div class="span10 well">
    <%= form_for(@report, :html => {:class => 'form-stacked'}) do |f| %>
      <fieldset>
        <div class="clearfix">
          <label>Name</label>
          <div class="input">
            <%= f.text_field :name, :class => "#{@report.errors.include?(:name) ? "f_error": ""}" %>
          </div>
        </div>

        <div class="clearfix">
          <label>Description</label>
          <div class="input">
            <%= f.text_area :description, :rows => "3", :class => "#{@report.errors.include?(:description) ? "f_error": ""}" %>
          </div>
        </div>

        <div class="clearfix">
          <label>Report period</label>
          <div class="input">
            <% current_start_date = @report.start_date && @report.start_date.strftime("%Y-%m") %>
            <%= f.text_field :start_date, :value => current_start_date || Time.now.strftime("%Y-%m"), :class => "span2 #{@report.errors.include?(:start_date) ? "f_error": ""}" %>
            to
            <% current_end_date = @report.end_date && @report.end_date.strftime("%Y-%m") %>
            <%= f.text_field :end_date, :value => current_end_date || (Time.now + 35.months).strftime("%Y-%m"), :class => "span2 #{@report.errors.include?(:end_date) ? "f_error": ""}" %>
            <span>The date range for which a report is required.</span>
          </div>
        </div>

        <div class="clearfix">
          <label>Report source</label>
          <div class="input">
            <%= f.hidden_field :reportable_type %>
            <%= f.collection_select :reportable_id, @reportables, :id, (@reportables.first.respond_to?(:name) ? :name : :id),
                                    {}, {:class => "span4 #{@report.errors.include?(:reportable_id) ? "f_error": ""}"} %>
            <span>The source model used to create the report.</span>
          </div>
        </div>

        <div class="clearfix">
          <div class="input">
            <%= f.submit "Create Report", :class =>'btn large primary' %>
          </div>
        </div>

      </fieldset>
  <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $("#report_start_date, #report_end_date").datepicker({
      dateFormat: 'yy-mm',
      changeMonth: true,
      changeYear: true,
      yearRange: '-0:+10',
      showButtonPanel: true,
      onClose: function(dateText, inst) {
        var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
        var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
        $(this).datepicker('setDate', new Date(year, month, 1));
      },
      beforeShow : function(input, inst) {
        if ((datestr = $(this).val()).length > 0) {
          actDate = datestr.split('-');
          year = actDate[0];
          month = actDate[1]-1;
          $(this).datepicker('option', 'defaultDate', new Date(year, month));
          $(this).datepicker('setDate', new Date(year, month));
        }
      }
    });
  });
</script>
<style>
  .ui-datepicker-calendar {
    display: none;
  }
</style>

app/views/reports/show.html.erb
<% editable_header @report, <<HELP
<p>This page shows the report contents. The report should be regenerated if its source model (e.g. deployment) has
changed and you would like to see an updated report.</p>
HELP
%>

<ul class="breadcrumb">
  <li>
    <%= link_to 'Print Report', print_report_path(@report), :method => :post, :class => 'btn' %>
    <span class="divider"></span>
  </li>
  <li>
    <%= link_to 'Regenerate Report', regenerate_report_path(@report), :method => :post, :class => 'btn' %>
    <span class="divider"></span>
  </li>
  <li>
    <%= link_to 'Delete Report', @report, :confirm => "OK to delete?", :method => :delete, :class => 'btn' %>
    <span class="divider"></span>
  </li>
  <li>
    <%= link_to @report.reportable.name, @report.reportable, :class => 'btn' unless @report.reportable.name.blank? %>
  </li>
</ul>

<%= @report.html.html_safe %>

<% if params[:action] == 'print' %>
  <script type="text/javascript">
    $(function() {window.print();});
  </script>
<% end %>